version: "3.9"
services:
  backend:
    image: orchestranexus/agentbox:TAG
    container_name: mw-backend
    command: uvicorn backend/agent_ws:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mailwhisperer
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MCP_SERVER_URL=${MCP_SERVER_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mw-db
    environment:
      POSTGRES_DB: mailwhisperer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  gmail:
    image: orchestranexus/gmail-mcp:v0.0.0
    command: bash -c "cd /root/.gmail-mcp/  && node /Gmail-MCP-Server-main/dist/index.js auth http://localhost:3000/oauth2callback & /scripts/start_bridge.sh"
    privileged: true
    tty: true
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./mcp/scripts:/scripts
      - ./mcp/scripts/gmail_auth.py:/root/gmail_auth.py
      - ./mcp/config:/config
      - ./auth/gcp-oauth.keys.json:/root/.gmail-mcp/gcp-oauth.keys.json
    environment:
      MCP_BRIDGE__CONFIG__FILE: /config/bridge_config.json

  frontend:
    image: mw-frontend:dev
    container_name: mw-frontend
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - db
      - backend

volumes:
  db_data:
